### ISSUE TITLE
train station names

### ISSUE THREAD

**Issue by Meddelin77** [mrVragec/MMM-mvgmunich#18]
Hiya

great module, thx a million. Exactly what I was looking for. 
Unfortunately only Hauptbahnhof works for me. I was trying to change it to Aufhausen and module is not defined. 
Any idea?

**Comment by Meddelin77** [comment]
also any plan to include disturbance (Stroeungsmeldungen?)

**Comment by mrVragec** [comment]
Hi @Meddelin77, 
thank you! 

If you are using 1.0.3 I think you should get an error string on display (something like: "Station Aufhausen is not correct, please update your config!. Hints for your station are: <empty>"). 
So this is clearly a bug in an old version, as hints are not visible. 
As this bug is already fixed in latest development version I would propose to switch to the 'dev' branch as long there is no new version available (I hope I will be able to release new version this week). 
Let me know if you will be able to switch to 'dev' branch and if it will work for you. 

The disturbance will be available in v1.0.5 (release around end of February).

**Comment by Meddelin77** [comment]
Hi mrVagec,

super looking forward to the disturbance. This is so cool!
I am brand new to Github , how can I switch to the dev branch?

**Comment by Meddelin77** [comment]
I had to re download it, and it works, soooo cool. Super Vielen dank
